name: Nifty Options Trading Bot

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    # Runs at 9:10 AM IST (3:40 AM UTC) Monday-Friday
    - cron: '40 3 * * 1-5'

jobs:
  trade:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Display IST time
      run: |
        echo "UTC Time: $(date -u)"
        echo "IST Time: $(TZ='Asia/Kolkata' date)"
    
    - name: Run trading bot
      run: python -u main.py
      timeout-minutes: 390
    
    - name: Upload trade logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: trade-logs-${{ github.run_number }}
        path: |
          nifty_cpr_trades.csv
          *.log
        retention-days: 30
        if-no-files-found: warn
